name: Unit Tests

on: [push,pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update and install PHP
      run: |
        sudo add-apt-repository ppa:ondrej/php
        sudo apt-get update
        sudo apt-get install
